port: 7880
bind_addresses:
  - "0.0.0.0"

keys:
  APIcA62hn2JKGHg: dbtqsLSMNVWM5yXjqkZRRSoFvNHRLbDtg5k5BOMV6PH
  devkey: "secretsecretspecified32byteslong!"

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50020
  use_external_ip: false
  stun_servers:
    - stun.l.google.com:19302
    - stun1.l.google.com:19302

redis:
  address: redis:6379
  db: 0

# Development settings
development: true
log_level: debug
