[general]
static=yes
writeprotect=no

[from-softphone]
; Dial 800 from MicroSIP/Zoiper to trigger the LiveKit Agent call
exten => 800,1,NoOp(Forwarding Call from Softphone to LiveKit Agent)
 same => n,Dial(PJSIP/800@livekit-trunk)
 same => n,Hangup()

[from-asterisk]
exten => _X.,1,NoOp(Handling Incoming SIP Traffic)
 same => n,Dial(PJSIP/${EXTEN}@livekit-trunk)
 same => n,Hangup()